name: RotatingMapSystem
version: '1.0-SNAPSHOT'
main: me.crunchycars.rotatingMapSystem.RotatingMapSystem
api-version: '1.19'
load: STARTUP

commands:
  adventure:
    description: Opens the adventure menu
    usage: /adventure
  giveIcyCavernsItem:
    description: Gives the player the Icy Caverns item.
    usage: giveIcyCavernsItem